command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: adb-30827331698809.9.azuredatabricks.net
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/610ea94e1066f95b
  - name: DATABRICKS_CATALOG
    value: ioc_sandbox
  - name: DATABRICKS_GOLD_SCHEMA
    value: geo_gold
  - name: DATABRICKS_SILVER_SCHEMA
    value: geo_silver
  - name: DATABRICKS_BRONZE_SCHEMA
    value: geo_bronze
  - name: DATABRICKS_CUSTOMER_PINS_TABLE
    value: ioc_sandbox.geo_gold.gis_customer_location_data
  - name: DATABRICKS_AGENT_ENDPOINT
    value: mas-7d62eac6-endpoint
