command:
  [
    "streamlit",
    "run",
    "app_v2.py",
    "--server.port",
    "8000",
    "--server.headless",
    "true",
  ]
env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: fe-vm-jdub-vm-serverless.cloud.databricks.com
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/0168e23e24e6ae10
  - name: DATABRICKS_TOKEN
    value_from: secret/databricks_token
  - name: DATABRICKS_CATALOG
    value: jdub_demo
  - name: DATABRICKS_BRONZE_SCHEMA
    value: geo_bronze
  - name: DATABRICKS_SILVER_SCHEMA
    value: geo_silver
  - name: DATABRICKS_GOLD_SCHEMA
    value: geo_gold
